docker-compose: set image to orbin/simh-vax
OrBin/simh-vax-docker pull request #1
Opened 2020-03-28 14:02 UTC by alkhimey

2020-03-29 09:56 UTC, OrBin requested changes

2020-03-29 09:56 UTC, OrBin commented on docker-compose.yml
> -    build: .
Can you leave it commented? when changing the dockerfile, we'd like to use this line for building automatically.

2020-03-31 06:57 UTC, OrBin approved these changes

2020-03-31 06:57 UTC, merged

2020-03-31 07:27 UTC, alkhimey commented
Sorry did not have time to do it in the last couple of days. I guess you will sort it out yourself 😉
Don't forget about the issue with changing the root directory from `simh-vax-docker` to `vax`.

2020-03-31 07:28 UTC, OrBin commented
Yeah, I've added a `build.sh` script to handle building

2020-03-31 07:28 UTC, OrBin commented
Thanks again!